# Generated by Django 5.0.6 on 2024-06-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_info', '0002_alter_language_comprehension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='comprehension',
            field=models.FloatField(),
        ),
    ]
