# Generated by Django 5.0.6 on 2024-06-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_info', '0003_alter_language_comprehension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('description', models.CharField(max_length=5110)),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
