# Generated by Django 5.0.6 on 2024-06-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_info', '0005_reflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
