# Generated by Django 5.0.6 on 2024-07-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_info', '0006_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='description',
            field=models.TextField(max_length=5110),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='gains',
            field=models.TextField(max_length=5110),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=520),
        ),
    ]
