# Generated by Django 5.0.6 on 2024-07-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_info', '0007_alter_reflection_description_alter_reflection_gains_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=5110),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=520),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(max_length=5110),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(max_length=5110),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=520),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(max_length=5110),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
