# Generated by Django 5.0.6 on 2024-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_info', '0010_userstats_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='backend_stat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='data_base_stat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='data_science_stat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='frontend_stat',
            field=models.IntegerField(default=0),
        ),
    ]
